version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.8
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 20s
      timeout: 10s
      retries: 5

  config:
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: asku-cloud/config
    ports:
      - 8888:8888
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy

  discovery:
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: asku-cloud/discovery
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761

  gateway:
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      JWT_SECRET_KEY: $JWT_SECRET_KEY
    build: asku-cloud/gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
      discovery:
        condition: service_healthy
    ports:
      - 4000:4000

  auth-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $AUTH_DB_PASSWORD
      MYSQL_DATABASE: authdb
    ports:
      - 3305:3306

  asku-auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      JWT_SECRET_KEY: $JWT_SECRET_KEY
      AUTH_DB_USERNAME: $AUTH_DB_USERNAME
      AUTH_DB_PASSWORD: $AUTH_DB_PASSWORD
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
    build: asku-auth-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
      discovery:
        condition: service_healthy
    ports:
      - 8889:8889

  account-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $ACCOUNT_DB_PASSWORD
      MYSQL_DATABASE: accountdb
    ports:
      - 3304:3306

  asku-account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_DB_USERNAME: $ACCOUNT_DB_USERNAME
      ACCOUNT_DB_PASSWORD: $ACCOUNT_DB_PASSWORD
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
    build: asku-account-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
      discovery:
        condition: service_healthy
    ports:
      - 8890:8890

  magazine-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MAGAZINE_DB_PASSWORD
      MYSQL_DATABASE: magazinedb
    ports:
      - 3303:3306

  asku-magazine-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MAGAZINE_DB_USERNAME: $MAGAZINE_DB_USERNAME
      MAGAZINE_DB_PASSWORD: $MAGAZINE_DB_PASSWORD
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
    build: asku-magazine-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
      discovery:
        condition: service_healthy
    ports:
      - 8891:8891
